name: cifar10_resnet18
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.1
  - torchvision=0.16.1
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - pyyaml=6.0.1
  - tqdm=4.65.0
  - scikit-learn=1.3.0
  - pillow=10.0.0
  - tensorboard=2.14.0
  - pip=23.2.1
  - pip:
    - torch-tb-profiler==0.4.1
    - wandb==0.15.8  # for experiment tracking
    - albumentations==1.3.1  # for advanced augmentations
    - timm==0.9.2  # for model architectures and training utilities 